export const CONFIG = {
  MIN_PLAYERS: 2,
  MAX_PLAYERS: 8,
  DEFAULT_TARGET_TIME: 3.0, // 3초
  MIN_TARGET_TIME: 1.0,
  MAX_TARGET_TIME: 10.0,
  QUICK_TAP_MIN_DELAY: 1000, // 1초
  QUICK_TAP_MAX_DELAY: 5000, // 5초
  TIMER_INTERVAL: 10, // 10ms
}
